baseurl: https://devcows.github.io/hugo-universal-theme/
title: Omics Medicine
theme: hugo-universal-theme
languageCode: en-us
defaultContentLanguage: en
disqusShortname: devcows
googleAnalytics: ''
summaryLength: 70
paginate: 10
pluralizelisttitles: no
menu:
  main:
    - identifier: menu.home
      name: Home
      url: /
      weight: 1
    - identifier: menu.blog
      name: Blog
      url: /blog/
      weight: 2
    - identifier: menu.faq
      name: Resources
      url: /resources/
      weight: 3
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 4
    - identifier: about
      name: About
      url: /about/
      weight: 5
  topbar:
  #  - name: Linkedin
  #    pre: <i class='fab fa-2x fa-linkedin'></i>
  #    url: https://www.linkedin.com/in/esmat-fazel-najafabadi-04b14553/?originalSubdomain=au
  #    weight: 1
    - name: Publons
      pre: <i class='fab fa-2x fa-publons'></i>
      url: https://publons.com/researcher/3290762/esmat-fazel-najafabadi/
      weight: 2
    - name: Email
      pre: <i class='fas fa-2x fa-envelope'></i>
      url: mailto:efazeln@gmail.com
      weight: 1
params:
  about_us: <p>Passionate About Human Genetics.</p>
 # address: "<p class=\"text-uppercase\"><strong>Universal Ltd.</strong>\n        <br>13/25
   # New Avenue\n        <br>Newtown upon River\n        <br>45Y 73J\n        <br>Iran\n
   # \       <br>\n        <strong>Great Britain</strong>\n      </p>\n      "
  author: esmfazel
  carouselCustomers:
    auto_play: no
    items: 6
    pagination_speed: 1000
    slide_speed: 2000
  carouselHomepage:
    auto_play: no
    enable: no
    pagination_speed: 1000
    slide_speed: 2000
  carouselTestimonials:
    auto_play: no
    items: 4
    pagination_speed: 1000
    slide_speed: 2000
  clients:
    enable: no
    subtitle: ''
    title: Our Clients
  contact_form_ajax: no
  contact_url: /contact
  copyright: Copyright (c) 2019, Omics Medicine; all rights reserved.
  date_format: January 2, 2006
  default_sharing_image: img/sharing-default.png
  defaultDescription: Site template made by Devcows using Hugo
  defaultKeywords:
    - devcows
    - hugo
    - go
  disabled_logo: no
  dropdown_mouse_over: no
  enableGoogleMaps: no
  enableRecaptchaInContactForm: no
  facebook_site: ''
  features:
    cols: 3
    enable: no
  footer:
    recent_posts:
      enable: no
  formspree_action: https://formspree.io/sample/of/endpoint
  googleMapsApiKey: AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY
  googleRecaptchaKey: site_key_for_google_recaptcha
  latitude: '-12.043333'
  logo: img/logo.png
  logo_small: img/logo-small.png
  logo_text: Universal
  longitude: '-77.028333'
  mainSections: blog
  recent_posts:
    enable: yes
    hide_summary: no
   # subtitle: Pellentesque habitant morbi tristique senectus et netus et malesuada
    #  fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget,
     # tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean
     # ultricies mi vitae est. Mauris placerat eleifend leo.
    title: From the blog
  see_more:
    enable: no
    icon: far fa-file-alt
    link_text: Check other homepages
    link_url: '#'
    subtitle: We have prepared for you more than 40 different HTML pages, including
      5 variations of homepage.
    title: Do you want to see more?
  style: default
  testimonials:
    enable: no
    subtitle: We have worked with many clients and we always like to hear they come
      out from the cooperation happy and satisfied. Have a look what our clients said
      about us.
    title: Testimonials
  topbar:
    enable: yes
    #text: "<p class=\"hidden-sm hidden-xs\">Contact us on +420 777 555 333 or hello@universal.com.</p>\n
     #\     <p class=\"hidden-md hidden-lg\"><a href=\"tel:+420 777 555 333\" data-animate-hover=\"pulse\"><i
    #  class=\"fas fa-phone\"></i></a>\n      <a href=\"mailto:hello@universal.com\"
    #  data-animate-hover=\"pulse\"><i class=\"fas fa-envelope\"></i></a>\n      </p>\n
     # \     "
  twitter_site: GoHugoIO
  viewMorePostLink: /blog/
  widgets:
    categories: no
    search: no
    tags: no
permalinks:
  blog: /blog/:year/:month/:day/:slug/
taxonomies:
  author: authors
  category: categories
  tag: tags

markup:
  goldmark:
    renderer:
      unsafe: true

